name: trigger-flood-pipeline

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */2 * * *' 

jobs:
  run-etl-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3


      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install nbconvert ipykernel
          # register a kernel named 'python3' so nbconvert can find it when executing the notebook
          python -m ipykernel install --user --name python3 --display-name "python3"

      - name: Executar notebook ETL
        env:
          NEON_CONNECTION_STRING: ${{ secrets.NEON_CONNECTION_STRING }}
        run: |
          python -m nbconvert --to notebook --execute flood_pipeline/ingestion.ipynb --ExecutePreprocessor.timeout=600 --output executed_ingestion.ipynb